// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DMX_Transmitter

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void coolAnimation_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_DMXScreen
void ui_DMXScreen_screen_init(void);
lv_obj_t * ui_DMXScreen;
lv_obj_t * ui_Buttons;
void ui_event_DMX(lv_event_t * e);
lv_obj_t * ui_DMX;
lv_obj_t * ui_DMXText;
void ui_event_Config(lv_event_t * e);
lv_obj_t * ui_Config;
lv_obj_t * ui_ConfigText;
void ui_event_About(lv_event_t * e);
lv_obj_t * ui_About;
lv_obj_t * ui_AboutText;
lv_obj_t * ui_Chart1;
lv_obj_t * ui_Chart1_Xaxis;
lv_obj_t * ui_Chart1_Yaxis1;
lv_obj_t * ui_Chart1_Yaxis2;
// CUSTOM VARIABLES


// SCREEN: ui_ConfigEbyte
void ui_ConfigEbyte_screen_init(void);
lv_obj_t * ui_ConfigEbyte;
lv_obj_t * ui_Titel4;
lv_obj_t * ui_UARTLabel;
lv_obj_t * ui_ParityLabel;
lv_obj_t * ui_AirLabel;
lv_obj_t * ui_PowerLabel;
lv_obj_t * ui_FECLabel;
lv_obj_t * ui_FixedLabel;
lv_obj_t * ui_WORLabel;
lv_obj_t * ui_IOLabel;
lv_obj_t * ui_ChannelLabel;
lv_obj_t * ui_ChannelValue;
void ui_event_submitConfigButton(lv_event_t * e);
lv_obj_t * ui_submitConfigButton;
lv_obj_t * ui_submitConfigText;
void ui_event_returnButton(lv_event_t * e);
lv_obj_t * ui_returnButton;
lv_obj_t * ui_returnButtonText;
lv_obj_t * ui_WarningLabel;
lv_obj_t * ui_UARTValue;
lv_obj_t * ui_ParityValue;
lv_obj_t * ui_AirrateValue;
lv_obj_t * ui_PowerValue;
lv_obj_t * ui_FECValue;
lv_obj_t * ui_TransparencyValue;
lv_obj_t * ui_WORValue;
lv_obj_t * ui_IOModeValue;
void ui_event_retrieveConfigButton(lv_event_t * e);
lv_obj_t * ui_retrieveConfigButton;
lv_obj_t * ui_retrieveConfigText;
// CUSTOM VARIABLES


// SCREEN: ui_ConfigScreen
void ui_ConfigScreen_screen_init(void);
lv_obj_t * ui_ConfigScreen;
lv_obj_t * ui_Buttons2;
void ui_event_DMX2(lv_event_t * e);
lv_obj_t * ui_DMX2;
lv_obj_t * ui_DMXText2;
void ui_event_Config2(lv_event_t * e);
lv_obj_t * ui_Config2;
lv_obj_t * ui_ConfigText2;
void ui_event_About1(lv_event_t * e);
lv_obj_t * ui_About1;
lv_obj_t * ui_AboutText1;
lv_obj_t * ui_channelSelector;
lv_obj_t * ui_channelOptionLabel;
void ui_event_startConfigButton(lv_event_t * e);
lv_obj_t * ui_startConfigButton;
lv_obj_t * ui_startConfigText;
lv_obj_t * ui_configLabel;
lv_obj_t * ui_delayOptionLabel;
lv_obj_t * ui_delaySpinbox;
void ui_event_delayPlus(lv_event_t * e);
lv_obj_t * ui_delayPlus;
lv_obj_t * ui_delayPlusText;
void ui_event_delayMinus(lv_event_t * e);
lv_obj_t * ui_delayMinus;
lv_obj_t * ui_delayMinusText;
void ui_event_saveGeneralSettingsButton(lv_event_t * e);
lv_obj_t * ui_saveGeneralSettingsButton;
lv_obj_t * ui_saveGeneralSettingsText;
// CUSTOM VARIABLES


// SCREEN: ui_AboutScreen
void ui_AboutScreen_screen_init(void);
lv_obj_t * ui_AboutScreen;
lv_obj_t * ui_Buttons3;
void ui_event_DMX3(lv_event_t * e);
lv_obj_t * ui_DMX3;
lv_obj_t * ui_DMXText3;
void ui_event_Config3(lv_event_t * e);
lv_obj_t * ui_Config3;
lv_obj_t * ui_ConfigText3;
void ui_event_About3(lv_event_t * e);
lv_obj_t * ui_About3;
lv_obj_t * ui_AboutText3;
lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void coolAnimation_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 300);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_0, 0, 100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 300);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_1, 0, -100);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_overshoot);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 300);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_image_zoom);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_DMX(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_DMXScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_DMXScreen_screen_init);
    }
}

void ui_event_Config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ConfigScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ConfigScreen_screen_init);
    }
}

void ui_event_About(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_AboutScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_AboutScreen_screen_init);
    }
}

void ui_event_submitConfigButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        submitConfigurationFunc(e);
    }
}

void ui_event_returnButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ConfigScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ConfigScreen_screen_init);
    }
}

void ui_event_retrieveConfigButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        retrieveConfigurationFunc(e);
    }
}

void ui_event_DMX2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_DMXScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_DMXScreen_screen_init);
    }
}

void ui_event_Config2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ConfigScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ConfigScreen_screen_init);
    }
}

void ui_event_About1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_AboutScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_AboutScreen_screen_init);
    }
}

void ui_event_startConfigButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ConfigEbyte, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ConfigEbyte_screen_init);
    }
}

void ui_event_delayPlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_delaySpinbox, 1);
    }
}

void ui_event_delayMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_delaySpinbox, -1);
    }
}

void ui_event_saveGeneralSettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        saveGeneralSettingsFunc(e);
    }
}

void ui_event_DMX3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_DMXScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_DMXScreen_screen_init);
    }
}

void ui_event_Config3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ConfigScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_ConfigScreen_screen_init);
    }
}

void ui_event_About3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_AboutScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_AboutScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_DMXScreen_screen_init();
    ui_ConfigEbyte_screen_init();
    ui_ConfigScreen_screen_init();
    ui_AboutScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_DMXScreen);
}
