// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DMX_Transmitter

#ifndef _DMX_TRANSMITTER_UI_H
#define _DMX_TRANSMITTER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void coolAnimation_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_DMXScreen
void ui_DMXScreen_screen_init(void);
extern lv_obj_t * ui_DMXScreen;
extern lv_obj_t * ui_Buttons;
void ui_event_DMX(lv_event_t * e);
extern lv_obj_t * ui_DMX;
extern lv_obj_t * ui_DMXText;
void ui_event_Config(lv_event_t * e);
extern lv_obj_t * ui_Config;
extern lv_obj_t * ui_ConfigText;
void ui_event_About(lv_event_t * e);
extern lv_obj_t * ui_About;
extern lv_obj_t * ui_AboutText;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
// CUSTOM VARIABLES

// SCREEN: ui_ConfigEbyte
void ui_ConfigEbyte_screen_init(void);
extern lv_obj_t * ui_ConfigEbyte;
extern lv_obj_t * ui_Titel4;
extern lv_obj_t * ui_UARTLabel;
extern lv_obj_t * ui_ParityLabel;
extern lv_obj_t * ui_AirLabel;
extern lv_obj_t * ui_PowerLabel;
extern lv_obj_t * ui_FECLabel;
extern lv_obj_t * ui_FixedLabel;
extern lv_obj_t * ui_WORLabel;
extern lv_obj_t * ui_IOLabel;
extern lv_obj_t * ui_ChannelLabel;
extern lv_obj_t * ui_ChannelValue;
void ui_event_submitConfigButton(lv_event_t * e);
extern lv_obj_t * ui_submitConfigButton;
extern lv_obj_t * ui_submitConfigText;
void ui_event_returnButton(lv_event_t * e);
extern lv_obj_t * ui_returnButton;
extern lv_obj_t * ui_returnButtonText;
extern lv_obj_t * ui_WarningLabel;
extern lv_obj_t * ui_UARTValue;
extern lv_obj_t * ui_ParityValue;
extern lv_obj_t * ui_AirrateValue;
extern lv_obj_t * ui_PowerValue;
extern lv_obj_t * ui_FECValue;
extern lv_obj_t * ui_TransparencyValue;
extern lv_obj_t * ui_WORValue;
extern lv_obj_t * ui_IOModeValue;
void ui_event_retrieveConfigButton(lv_event_t * e);
extern lv_obj_t * ui_retrieveConfigButton;
extern lv_obj_t * ui_retrieveConfigText;
// CUSTOM VARIABLES

// SCREEN: ui_ConfigScreen
void ui_ConfigScreen_screen_init(void);
extern lv_obj_t * ui_ConfigScreen;
extern lv_obj_t * ui_Buttons2;
void ui_event_DMX2(lv_event_t * e);
extern lv_obj_t * ui_DMX2;
extern lv_obj_t * ui_DMXText2;
void ui_event_Config2(lv_event_t * e);
extern lv_obj_t * ui_Config2;
extern lv_obj_t * ui_ConfigText2;
void ui_event_About1(lv_event_t * e);
extern lv_obj_t * ui_About1;
extern lv_obj_t * ui_AboutText1;
extern lv_obj_t * ui_channelSelector;
extern lv_obj_t * ui_channelOptionLabel;
void ui_event_startConfigButton(lv_event_t * e);
extern lv_obj_t * ui_startConfigButton;
extern lv_obj_t * ui_startConfigText;
extern lv_obj_t * ui_configLabel;
extern lv_obj_t * ui_delayOptionLabel;
extern lv_obj_t * ui_delaySpinbox;
void ui_event_delayPlus(lv_event_t * e);
extern lv_obj_t * ui_delayPlus;
extern lv_obj_t * ui_delayPlusText;
void ui_event_delayMinus(lv_event_t * e);
extern lv_obj_t * ui_delayMinus;
extern lv_obj_t * ui_delayMinusText;
void ui_event_saveGeneralSettingsButton(lv_event_t * e);
extern lv_obj_t * ui_saveGeneralSettingsButton;
extern lv_obj_t * ui_saveGeneralSettingsText;
// CUSTOM VARIABLES

// SCREEN: ui_AboutScreen
void ui_AboutScreen_screen_init(void);
extern lv_obj_t * ui_AboutScreen;
extern lv_obj_t * ui_Buttons3;
void ui_event_DMX3(lv_event_t * e);
extern lv_obj_t * ui_DMX3;
extern lv_obj_t * ui_DMXText3;
void ui_event_Config3(lv_event_t * e);
extern lv_obj_t * ui_Config3;
extern lv_obj_t * ui_ConfigText3;
void ui_event_About3(lv_event_t * e);
extern lv_obj_t * ui_About3;
extern lv_obj_t * ui_AboutText3;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_2021007708);    // assets/Logo-website-retina.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
