// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DMX_Transmitter

#include "ui.h"

void ui_AboutScreen_screen_init(void)
{
    ui_AboutScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AboutScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Buttons3 = lv_obj_create(ui_AboutScreen);
    lv_obj_remove_style_all(ui_Buttons3);
    lv_obj_set_width(ui_Buttons3, lv_pct(100));
    lv_obj_set_height(ui_Buttons3, lv_pct(20));
    lv_obj_remove_flag(ui_Buttons3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Buttons3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttons3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttons3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Buttons3, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DMX3 = lv_button_create(ui_Buttons3);
    lv_obj_set_width(ui_DMX3, lv_pct(30));
    lv_obj_set_height(ui_DMX3, lv_pct(96));
    lv_obj_set_x(ui_DMX3, lv_pct(1));
    lv_obj_set_y(ui_DMX3, lv_pct(2));
    lv_obj_add_flag(ui_DMX3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DMX3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_DMX3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_DMX3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DMX3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_DMX3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DMX3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DMX3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DMX3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DMXText3 = lv_label_create(ui_DMX3);
    lv_obj_set_width(ui_DMXText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DMXText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DMXText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DMXText3, "DMX");

    ui_Config3 = lv_button_create(ui_Buttons3);
    lv_obj_set_width(ui_Config3, lv_pct(30));
    lv_obj_set_height(ui_Config3, lv_pct(96));
    lv_obj_set_x(ui_Config3, lv_pct(35));
    lv_obj_set_y(ui_Config3, lv_pct(2));
    lv_obj_add_flag(ui_Config3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Config3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Config3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Config3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Config3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Config3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Config3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Config3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigText3 = lv_label_create(ui_Config3);
    lv_obj_set_width(ui_ConfigText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfigText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfigText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfigText3, "Config");

    ui_About3 = lv_button_create(ui_Buttons3);
    lv_obj_set_width(ui_About3, lv_pct(30));
    lv_obj_set_height(ui_About3, lv_pct(96));
    lv_obj_set_x(ui_About3, lv_pct(69));
    lv_obj_set_y(ui_About3, lv_pct(2));
    lv_obj_add_state(ui_About3, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_About3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_About3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_About3, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_About3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_About3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_About3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_About3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_About3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_About3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutText3 = lv_label_create(ui_About3);
    lv_obj_set_width(ui_AboutText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AboutText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AboutText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AboutText3, "About");

    ui_Image1 = lv_image_create(ui_AboutScreen);
    lv_image_set_src(ui_Image1, &ui_img_2021007708);
    lv_obj_set_width(ui_Image1, lv_pct(100));
    lv_obj_set_height(ui_Image1, lv_pct(78));
    lv_obj_set_x(ui_Image1, lv_pct(0));
    lv_obj_set_y(ui_Image1, lv_pct(22));
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_DMX3, ui_event_DMX3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Config3, ui_event_Config3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_About3, ui_event_About3, LV_EVENT_ALL, NULL);

}
