// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DMX_Transmitter

#include "ui.h"

void ui_ConfigScreen_screen_init(void)
{
    ui_ConfigScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ConfigScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Buttons2 = lv_obj_create(ui_ConfigScreen);
    lv_obj_remove_style_all(ui_Buttons2);
    lv_obj_set_width(ui_Buttons2, lv_pct(100));
    lv_obj_set_height(ui_Buttons2, lv_pct(20));
    lv_obj_remove_flag(ui_Buttons2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Buttons2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttons2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttons2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Buttons2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DMX2 = lv_button_create(ui_Buttons2);
    lv_obj_set_width(ui_DMX2, lv_pct(30));
    lv_obj_set_height(ui_DMX2, lv_pct(96));
    lv_obj_set_x(ui_DMX2, lv_pct(1));
    lv_obj_set_y(ui_DMX2, lv_pct(2));
    lv_obj_add_flag(ui_DMX2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DMX2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_DMX2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_DMX2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DMX2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_DMX2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DMX2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DMX2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DMX2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DMXText2 = lv_label_create(ui_DMX2);
    lv_obj_set_width(ui_DMXText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DMXText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DMXText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DMXText2, "DMX");

    ui_Config2 = lv_button_create(ui_Buttons2);
    lv_obj_set_width(ui_Config2, lv_pct(30));
    lv_obj_set_height(ui_Config2, lv_pct(96));
    lv_obj_set_x(ui_Config2, lv_pct(35));
    lv_obj_set_y(ui_Config2, lv_pct(2));
    lv_obj_add_state(ui_Config2, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_Config2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Config2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Config2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Config2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Config2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Config2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Config2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Config2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigText2 = lv_label_create(ui_Config2);
    lv_obj_set_width(ui_ConfigText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfigText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfigText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfigText2, "Config");

    ui_About1 = lv_button_create(ui_Buttons2);
    lv_obj_set_width(ui_About1, lv_pct(30));
    lv_obj_set_height(ui_About1, lv_pct(96));
    lv_obj_set_x(ui_About1, lv_pct(69));
    lv_obj_set_y(ui_About1, lv_pct(2));
    lv_obj_add_flag(ui_About1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_About1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_About1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_About1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_About1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_About1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_About1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_About1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_About1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutText1 = lv_label_create(ui_About1);
    lv_obj_set_width(ui_AboutText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AboutText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AboutText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AboutText1, "About");

    ui_channelSelector = lv_roller_create(ui_ConfigScreen);
    lv_roller_set_options(ui_channelSelector,
                          "1-54\n55-108\n109-162\n163-216\n217-270\n271-324\n325-378\n379-432\n433-486\n487-512", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_channelSelector, 120);
    lv_obj_set_width(ui_channelSelector, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_channelSelector, lv_pct(4));
    lv_obj_set_y(ui_channelSelector, lv_pct(34));

    ui_channelOptionLabel = lv_label_create(ui_ConfigScreen);
    lv_obj_set_width(ui_channelOptionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_channelOptionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_channelOptionLabel, lv_pct(5));
    lv_obj_set_y(ui_channelOptionLabel, lv_pct(24));
    lv_label_set_text(ui_channelOptionLabel, "Channels");
    lv_obj_set_style_text_font(ui_channelOptionLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startConfigButton = lv_button_create(ui_ConfigScreen);
    lv_obj_set_height(ui_startConfigButton, 120);
    lv_obj_set_width(ui_startConfigButton, lv_pct(32));
    lv_obj_set_x(ui_startConfigButton, lv_pct(32));
    lv_obj_set_y(ui_startConfigButton, lv_pct(34));
    lv_obj_add_flag(ui_startConfigButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_startConfigButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_startConfigButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_startConfigButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_startConfigButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_startConfigButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_startConfigButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startConfigText = lv_label_create(ui_startConfigButton);
    lv_obj_set_width(ui_startConfigText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startConfigText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_startConfigText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startConfigText, "Start Config");

    ui_configLabel = lv_label_create(ui_ConfigScreen);
    lv_obj_set_width(ui_configLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_configLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_configLabel, lv_pct(32));
    lv_obj_set_y(ui_configLabel, lv_pct(24));
    lv_label_set_text(ui_configLabel, "Configure EByte");
    lv_obj_set_style_text_font(ui_configLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_delayOptionLabel = lv_label_create(ui_ConfigScreen);
    lv_obj_set_width(ui_delayOptionLabel, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_delayOptionLabel, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_delayOptionLabel, lv_pct(78));
    lv_obj_set_y(ui_delayOptionLabel, lv_pct(24));
    lv_label_set_text(ui_delayOptionLabel, "Delay");
    lv_obj_set_style_text_font(ui_delayOptionLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_delaySpinbox = lv_spinbox_create(ui_ConfigScreen);
    lv_obj_set_width(ui_delaySpinbox, lv_pct(24));
    lv_obj_set_height(ui_delaySpinbox, lv_pct(12));
    lv_obj_set_x(ui_delaySpinbox, lv_pct(72));
    lv_obj_set_y(ui_delaySpinbox, lv_pct(38));
    lv_spinbox_set_digit_format(ui_delaySpinbox, 4, 0);
    lv_spinbox_set_range(ui_delaySpinbox, 1, 255);
    lv_spinbox_set_cursor_pos(ui_delaySpinbox, 1 - 1);

    ui_delayPlus = lv_button_create(ui_ConfigScreen);
    lv_obj_set_width(ui_delayPlus, lv_pct(10));
    lv_obj_set_height(ui_delayPlus, lv_pct(14));
    lv_obj_set_x(ui_delayPlus, lv_pct(86));
    lv_obj_set_y(ui_delayPlus, lv_pct(54));
    lv_obj_add_flag(ui_delayPlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_delayPlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_delayPlus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_delayPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_delayPlus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_delayPlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_delayPlus, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_delayPlusText = lv_label_create(ui_delayPlus);
    lv_obj_set_width(ui_delayPlusText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_delayPlusText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_delayPlusText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_delayPlusText, "+");

    ui_delayMinus = lv_button_create(ui_ConfigScreen);
    lv_obj_set_width(ui_delayMinus, lv_pct(10));
    lv_obj_set_height(ui_delayMinus, lv_pct(14));
    lv_obj_set_x(ui_delayMinus, lv_pct(72));
    lv_obj_set_y(ui_delayMinus, lv_pct(54));
    lv_obj_add_flag(ui_delayMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_delayMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_delayMinus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_delayMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_delayMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_delayMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_delayMinus, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_delayMinusText = lv_label_create(ui_delayMinus);
    lv_obj_set_width(ui_delayMinusText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_delayMinusText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_delayMinusText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_delayMinusText, "-");

    ui_saveGeneralSettingsButton = lv_button_create(ui_ConfigScreen);
    lv_obj_set_width(ui_saveGeneralSettingsButton, 100);
    lv_obj_set_height(ui_saveGeneralSettingsButton, 40);
    lv_obj_set_x(ui_saveGeneralSettingsButton, lv_pct(75));
    lv_obj_set_y(ui_saveGeneralSettingsButton, lv_pct(81));
    lv_obj_add_flag(ui_saveGeneralSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_saveGeneralSettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_saveGeneralSettingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_saveGeneralSettingsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_saveGeneralSettingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_saveGeneralSettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_saveGeneralSettingsButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_saveGeneralSettingsText = lv_label_create(ui_saveGeneralSettingsButton);
    lv_obj_set_width(ui_saveGeneralSettingsText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_saveGeneralSettingsText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_saveGeneralSettingsText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_saveGeneralSettingsText, "Save");

    lv_obj_add_event_cb(ui_DMX2, ui_event_DMX2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Config2, ui_event_Config2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_About1, ui_event_About1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_startConfigButton, ui_event_startConfigButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_delayPlus, ui_event_delayPlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_delayMinus, ui_event_delayMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_saveGeneralSettingsButton, ui_event_saveGeneralSettingsButton, LV_EVENT_ALL, NULL);

}
