// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DMX_Transmitter

#include "ui.h"

void ui_DMXScreen_screen_init(void)
{
    ui_DMXScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DMXScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Buttons = lv_obj_create(ui_DMXScreen);
    lv_obj_remove_style_all(ui_Buttons);
    lv_obj_set_width(ui_Buttons, lv_pct(100));
    lv_obj_set_height(ui_Buttons, lv_pct(20));
    lv_obj_remove_flag(ui_Buttons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Buttons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Buttons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Buttons, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Buttons, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DMX = lv_button_create(ui_Buttons);
    lv_obj_set_width(ui_DMX, lv_pct(30));
    lv_obj_set_height(ui_DMX, lv_pct(96));
    lv_obj_set_x(ui_DMX, lv_pct(1));
    lv_obj_set_y(ui_DMX, lv_pct(2));
    lv_obj_add_state(ui_DMX, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_DMX, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DMX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_DMX, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_DMX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DMX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_DMX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DMX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DMX, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DMX, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DMXText = lv_label_create(ui_DMX);
    lv_obj_set_width(ui_DMXText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DMXText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DMXText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DMXText, "DMX");

    ui_Config = lv_button_create(ui_Buttons);
    lv_obj_set_width(ui_Config, lv_pct(30));
    lv_obj_set_height(ui_Config, lv_pct(96));
    lv_obj_set_x(ui_Config, lv_pct(35));
    lv_obj_set_y(ui_Config, lv_pct(2));
    lv_obj_add_flag(ui_Config, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Config, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Config, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Config, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Config, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Config, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Config, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Config, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigText = lv_label_create(ui_Config);
    lv_obj_set_width(ui_ConfigText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfigText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfigText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfigText, "Config");

    ui_About = lv_button_create(ui_Buttons);
    lv_obj_set_width(ui_About, lv_pct(30));
    lv_obj_set_height(ui_About, lv_pct(96));
    lv_obj_set_x(ui_About, lv_pct(69));
    lv_obj_set_y(ui_About, lv_pct(2));
    lv_obj_add_flag(ui_About, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_About, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_About, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_About, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_About, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_About, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_About, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_About, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutText = lv_label_create(ui_About);
    lv_obj_set_width(ui_AboutText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AboutText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AboutText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AboutText, "About");

    ui_Chart1 = lv_chart_create(ui_DMXScreen);
    lv_obj_set_width(ui_Chart1, lv_pct(96));
    lv_obj_set_height(ui_Chart1, lv_pct(74));
    lv_obj_set_x(ui_Chart1, lv_pct(2));
    lv_obj_set_y(ui_Chart1, lv_pct(24));
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart1, 54);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 255);
    lv_chart_set_div_line_count(ui_Chart1, 25, 54);

    ui_Chart1_Xaxis = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart1_Xaxis, lv_pct(100), 1);
    lv_obj_set_align(ui_Chart1_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart1_Xaxis, 1 + lv_obj_get_style_pad_bottom(ui_Chart1,
                                                                  LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart1_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart1_Xaxis, 0, 54 > 0 ? 54 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart1_Xaxis, (54 > 0 ? 54 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Xaxis, 1 >= 1 ? 1 : 1);
    lv_scale_set_label_show(ui_Chart1_Xaxis, false);
    ui_Chart1_Yaxis1 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart1_Yaxis1, 40, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis1, -40 - lv_obj_get_style_pad_left(ui_Chart1,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart1_Yaxis1,  0, 255);
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis1, (12 > 0 ? 12 - 1 : 0) * 1 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis1, 1 >= 1 ? 1 : 1);
    lv_scale_set_label_show(ui_Chart1_Yaxis1, false);
    ui_Chart1_Yaxis2 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart1_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_Chart1_Yaxis2, false);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x00FFF8),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);



    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart1, LV_MAX3(1, 40, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_DMX, ui_event_DMX, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Config, ui_event_Config, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_About, ui_event_About, LV_EVENT_ALL, NULL);

}
