// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: DMX_Transmitter

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void submitConfigurationFunc(lv_event_t * e);
void retrieveConfigurationFunc(lv_event_t * e);
void saveGeneralSettingsFunc(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
